### ISSUE TITLE
GitHub Actionsに対しては，Renovateが毎月最初の週末にPRを投げるように設定する

### ISSUE THREAD

**Issue by femshima** [jpreprocess/jpreprocess#107]
わざわざCommit SHAで指定しているのにRenovateが毎週更新を迫ってきたら意味がないので…

**Comment by Mogyuchi** [comment]
んー
最新に追従すべきとCommit SHA を指定すべきは両立するんよ…

**Comment by femshima** [comment]
それは更新時に中身をちゃんとチェックしたら，の話であり，僕はそれを徹底できる自信がない．

**Comment by Mogyuchi** [comment]
https://docs.renovatebot.com/presets-default/#onlynpm のように、
`"github-actions": false`を入れておけば良さそう？

**Comment by Mogyuchi** [comment]
後で確認する

**Comment by femshima** [comment]
方針変更：「RenovateがGitHub Actionsを無視するように設定する」→「毎月最初の週末にPRを投げるようにする」
